/* tslint:disable */
/* eslint-disable */
/**
 * Welcome to Haven - OpenAPI 3.0
 * This openapi spec contains details for apis in Haven
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EvacuationPoint
 */
export interface EvacuationPoint {

    /**
     * @type {number}
     * @memberof EvacuationPoint
     * @example 10
     */
    id?: number;

    /**
     * @type {string}
     * @memberof EvacuationPoint
     * @example Near George Street
     */
    location?: string;
}
