/* tslint:disable */
/* eslint-disable */
/**
 * Welcome to Haven - OpenAPI 3.0
 * This openapi spec contains details for apis in Haven
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Feed
 */
export interface Feed {

    /**
     * @type {number}
     * @memberof Feed
     * @example 10
     */
    id?: number;

    /**
     * @type {number}
     * @memberof Feed
     * @example 123
     */
    userId?: number;

    /**
     * @type {string}
     * @memberof Feed
     * @example need help around olympic park
     */
    description?: string;

    /**
     * @type {string}
     * @memberof Feed
     * @example James
     */
    createdAt?: string;

    /**
     * @type {string}
     * @memberof Feed
     * @example john@email.com
     */
    deletedAt?: string;

    /**
     * @type {string}
     * @memberof Feed
     * @example olympic park
     */
    location?: string;

    /**
     * Feed Status
     *
     * @type {number}
     * @memberof Feed
     * @example 1
     */
    status?: number;
}
