/* tslint:disable */
/* eslint-disable */
/**
 * Welcome to Haven - OpenAPI 3.0
 * This openapi spec contains details for apis in Haven
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EvacuationPoint } from '../models';
/**
 * SafeSpaceSuggesterApi - axios parameter creator
 * @export
 */
export const SafeSpaceSuggesterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get service by its location.
         * @param {any} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        safeSpaceSuggesterGet: async (location: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'location' is not null or undefined
            if (location === null || location === undefined) {
                throw new RequiredError('location','Required parameter location was null or undefined when calling safeSpaceSuggesterGet.');
            }
            const localVarPath = `/safe-space-suggester`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SafeSpaceSuggesterApi - functional programming interface
 * @export
 */
export const SafeSpaceSuggesterApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get service by its location.
         * @param {any} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async safeSpaceSuggesterGet(location: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EvacuationPoint>>> {
            const localVarAxiosArgs = await SafeSpaceSuggesterApiAxiosParamCreator(configuration).safeSpaceSuggesterGet(location, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SafeSpaceSuggesterApi - factory interface
 * @export
 */
export const SafeSpaceSuggesterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get service by its location.
         * @param {any} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async safeSpaceSuggesterGet(location: any, options?: AxiosRequestConfig): Promise<AxiosResponse<EvacuationPoint>> {
            return SafeSpaceSuggesterApiFp(configuration).safeSpaceSuggesterGet(location, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SafeSpaceSuggesterApi - object-oriented interface
 * @export
 * @class SafeSpaceSuggesterApi
 * @extends {BaseAPI}
 */
export class SafeSpaceSuggesterApi extends BaseAPI {
    /**
     * 
     * @summary Get service by its location.
     * @param {any} location 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SafeSpaceSuggesterApi
     */
    public async safeSpaceSuggesterGet(location: any, options?: AxiosRequestConfig) : Promise<AxiosResponse<EvacuationPoint>> {
        return SafeSpaceSuggesterApiFp(this.configuration).safeSpaceSuggesterGet(location, options).then((request) => request(this.axios, this.basePath));
    }
}
